# 7PAVITPR: Introduction to Statistical Programming
# Python practical 11


_Department of Biostatistics and Health Informatics<br/>
Institute of Psychiatry, Psychology and Neuroscience<br/>
King's College London<br/>_


_Acknowledgment: based on parts of the course "Big Data Analytics in Python", written by Saga Jilka, KCL_

# Pandas

__NOTE__ This notebook assumes the files brain_clinic_measures.csv and brain_participant_info.csv are in the same directory as the notebook. If you are using colab, you will need to upload the files to your colab session. If you are using Jupyter Notebook, you will need to make sure the files are in the same directory as the notebook.

Python has many powerful packages to help us analyse data. Pandas is one of the most commonly used.

Pandas stands for “Python Data Analysis Library”. It's great for dealing with spreadsheet-style data – by creating ‘Dataframes’. You can then easily select columns from datasets and apply functions to them.

We will show how you can use pandas to manipulate and prepare data, and do some simple procesisng, using a brain volume and IQ data set. The plan is to:

1. Read in two csv files for analysis

2. Explore the data with pandas dataframes

3. Clean and pre-process data (e.g. fill missing values)

4. Compute some basic stats

5. Merge datasets

6. Aggregate data



## <font color=green>❓ Question</font>
Import pandas.

## <font color=green>⌨️ Your answer</font>

In [1]:
# Your Anaconda Python distribution comes with Pandas ready to use.
# All you have to do to use it is ‘import’ pandas.
# A commonly used abbreviation for Pandas is ‘pd’, and we will use this.

# Import pandas...
# YOU WRITE THIS
import pandas as pd

## Data

Pandas can import all sorts of files.


## <font color=green>💬 Discussion point</font>

Take a look at the [Pandas user guide](https://pandas.pydata.org/pandas-docs/stable/user_guide/index.html). What file formats are available?


### DataFrames
Files are read in to a `DataFrame` object. You can think of this as a table, with column headings and row numbers. Each row is a `Series` object. Much of Pandas useage is about manipulating `DataFrames` and `Series` objects.


## <font color=green>💬 Discussion point</font>

The method to read a csv file is `read_csv()`. How do you think it works?

## Reading in data

We will read in our fist file, a set of clinic measurements from participants in a brain study.

## <font color=green>❓ Question</font>
Using the method `read_csv()`, read the file `brain_clinic_measures.csv` in to a DataFrame called `df_m`. Apart from the file name, you shouldn't need any arguments.

What object is the method going to be applied to?

## <font color=green>⌨️ Your answer</font>

In [3]:
# Complete the code below, to read in the CSV file
# df_m = MODULE.METHOD(FILE)
df_m = pd.read_csv('/content/brain_clinic_measures (1).txt')

## Viewing data

There are a few ways to look at the data. For example, for a `DataFrame` called `df`:

- `print(df)` - prints the  whole lot
- `df.ndim` -  the number of dimensions (N.B. no brackets - an attribute, not a method)
- `df.shape` - the size of each dimension (N.B. no brackets - an attribute, not a method)
- `df.head()` - first 5 rows
- `df.head(3)` - first 3 rows
- `df.tail()` - last 5 rows
- `df.tail(3)` - last 3 rows
- `df.dtypes` - data types of the columns (N.B. no brackets - an attribute, not a method)
- `df.describe()` - some stats

## <font color=green>❓ Question</font>
Using these methods and attributes:

- find the size of the dataset
- find the names of the columns
- look at some examples of the data
- get some summary statistics

In order that you see all of your results in the notebook, you will find it easier to split your code across several cells. e.g. have a cell looking at the head of the data, then a cell with other display commands. You might want to do this other parts of the exercise, too.

## <font color=green>⌨️ Your answer</font>

In [4]:
# Explore the data, writing your own code in the folowing cells,
# to print out some of its features
df_m.head()
print(df_m.shape)
print(df_m.columns)
print(df_m.head())
print(df_m.describe())

(40, 6)
Index(['Unnamed: 0', 'ppt_id', 'FSIQ', 'VIQ', 'PIQ', 'MRI_Count'], dtype='object')
   Unnamed: 0  ppt_id  FSIQ  VIQ  PIQ  MRI_Count
0           0       1   133  132  124     816932
1           1       2   140  150  124    1001121
2           2       3   139  123  150    1038437
3           3       4   133  129  128     965353
4           4       5   137  132  134     951545
       Unnamed: 0     ppt_id        FSIQ         VIQ        PIQ     MRI_Count
count   40.000000  40.000000   40.000000   40.000000   40.00000  4.000000e+01
mean    19.500000  20.500000  113.450000  112.350000  111.02500  9.087550e+05
std     11.690452  11.690452   24.082071   23.616107   22.47105  7.228205e+04
min      0.000000   1.000000   77.000000   71.000000   72.00000  7.906190e+05
25%      9.750000  10.750000   89.750000   90.000000   88.25000  8.559185e+05
50%     19.500000  20.500000  116.500000  113.000000  115.00000  9.053990e+05
75%     29.250000  30.250000  135.500000  129.750000  128.00000  9.500780e+05
max     39.000000  40.000000  144.000000  150.000000  150.00000  1.079549e+06

## Selecting data

There are multiple ways to select data. The simplest uses slices or column names. Look at the following two examples and try them:

In [5]:
# Some examples of selecting data

# select some rows: a slice
df_m[0:10:2]

   Unnamed: 0  ppt_id  FSIQ  VIQ  PIQ  MRI_Count
0           0       1   133  132  124     816932
2           2       3   139  123  150    1038437
4           4       5   137  132  134     951545
6           6       7   138  136  131     991305
8           8       9    89   93   84     904858

In [6]:
# Some examples of selecting data

# select a column: using an attribute for a column name
# (we've added head(3) for compact output)
df_m.PIQ.head(3)

0    124
1    124
2    150
Name: PIQ, dtype: int64

In [7]:
# Some examples of selecting data

# select several columns: using a list of column names
# (we've added head(3) for compact output)
df_m[['ppt_id', 'PIQ', 'VIQ']].head(3)

   ppt_id  PIQ  VIQ
0       1  124  132
1       2  124  150
2       3  150  123

## <font color=green>💬 Discussion point</font>

- What does the first of the above examples do?
- What type of object does the first and third examples return?


The second example returns a single column, which is one dimensional.

### Series

One dimensional data objects in Pandas are modelled by class `Series`. Examples are:

- single columns from DataFrames
- single rows from DataFrames

The `Series` class supports a large number of methods. Examples include:

- `sum()`
- `mean()`
- `count()`
- `max()`
- `min()`
- `nunique()`
- `fillna()`

See [the documentation](https://pandas.pydata.org/pandas-docs/stable/reference/series.html) for a full list.

## <font color=green>💬 Discussion point</font>
Most of the above `Series` methods are self-explanatory. But what to the last two, `nunique()` and `fillna()` do?

## Combining selection operators

We can combine the above operators, for example:

In [8]:
# Get a slice of one column

df_m.PIQ[0:10:2]

0    124
2    150
4    134
6    131
8     84
Name: PIQ, dtype: int64

In [9]:
# Get one column of a slice

df_m[0:10:2].PIQ

0    124
2    150
4    134
6    131
8     84
Name: PIQ, dtype: int64

## <font color=green>❓ Question</font>
Write a statement that selects every other row from the 1st to the 9th, for just columns ppt_id, PIQ and VIQ

## <font color=green>⌨️ Your answer</font>

In [10]:
# Write your answer below
df_m[['ppt_id','PIQ','VIQ']][0:9]

   ppt_id  PIQ  VIQ
0       1  124  132
1       2  124  150
2       3  150  123
3       4  128  129
4       5  134  132
5       6  110   90
6       7  131  136
7       8   98   90
8       9   84   93

## Better selection

Although the above selection methods are intuitive to use in a notebook, they are also inneficient, and so best not used for production code. Pandas data objects also have attributes that give access to faster indexes - known as _location based indexes_. These hold additional information, and optimised access to the underlying data.

The two attributes are:

- `loc` - use this for selection by label
- `iloc` - use this for selection by index number

These are used with _indexers_, which are placed in square brackets and look very much like slice operators:

- `Series`	- `s.loc[indexer]`
- `DataFrame`	- `df.loc[row_indexer,column_indexer]`

(the same works for iloc)

Examples of indexers are:

- explicit index of a row - `2`
- lists of explicit column indices - `[1, 4, 5]`
- column names - `ppt_id`
- lists of column names - `['ppt_id', 'PIQ']`
- slices of rows - `2:10:2`

Below are a couple of examples: try them.

In [11]:
# selecting just columns - select everything with the row indexer
df_m.iloc[:,[1,2,3]].head(3)

   ppt_id  FSIQ  VIQ
0       1   133  132
1       2   140  150
2       3   139  123

In [12]:
# selecting just rows
df_m.iloc[4:7]

   Unnamed: 0  ppt_id  FSIQ  VIQ  PIQ  MRI_Count
4           4       5   137  132  134     951545
5           5       6    99   90  110     928799
6           6       7   138  136  131     991305

## <font color=green>❓ Question</font>
Write a statement that uses loc to select the 10th to 15th rows for columns ppt_id and MRI_Count

## <font color=green>⌨️ Your answer</font>

In [13]:
# Write your answer here
df_m.loc[9:14, ['ppt_id','MRI_Count']]

    ppt_id  MRI_Count
9       10     955466
10      11     833868
11      12    1079549
12      13     924059
13      14     856472
14      15     878897

## <font color=green>💬 Discussion point</font>
Can you notice a difference between the way index numbers apply in slices and in Pandas indexers? Try a few code examlpes to see if you can spot it.

## Logical selectors

`loc` indexers can also be logical selectors - selectors that return a truth value. The example below illustrates this:

In [14]:
# Select all rows where PIQ is above 140

df_m.loc[df_m.PIQ > 140]

    Unnamed: 0  ppt_id  FSIQ  VIQ  PIQ  MRI_Count
2            2       3   139  123  150    1038437
9            9      10   133  114  147     955466
13          13      14   140  120  147     856472

### Interlude: understanding truth values in DataFrames


- Up to now, we have used `and`, `or` etc. to combine truth values.
- `and`, `or` test whether things are _logically true_
- Python defines anything that is not empty to be _logically true_

Try the following code:

In [15]:
print( False and True )
print( [False] and True )

False
True

This behaviour is problematic when we want to do vector operations. Pandas uses NumPy vectors under the hood, which do not support the notion of logical truth. This is because it makes no sense when trying to combine two vectors of truth values, as both vectors are True. Instead, NumPy and Pandas override the bitwise operators such as &, |, to do element by element comparison of vector values.


- `&` - bitwise and
- `|` - bitwise or

(there are other bitwise operators - see the [Python docs](https://docs.python.org/3/library/stdtypes.html#bitwise-operations-on-integer-types) if needed)


We also have to account for the fact that bitwise operators are higher precedence than comparison operators. So if we have:

`10 < 2 & 10 < 100`

the `2 & 10` is evaluated first.

To get the correct evaluation, we use parentheses, as these have a higher priority than `&`, `|`:

`(10 < 2) & (10 < 100)`

## <font color=green>❓ Question</font>
Write a statement that uses loc to select ppt_id, FSIQ and PIQ where PIQ is greater than 130, and FSIQ less than 140.

__Hint:__ you will need to combine two truth expressions with `&`. When you do, place parentheses around each of the two truth expressions

## <font color=green>⌨️ Your answer</font>

In [16]:
# Your answer here - like the one below:
# df_m.loc[(EXPRESSON 1) & (EXPRESSION 2), [COLUMN INDEXER HERE]]
df_m.loc[(df_m['PIQ'] > 130) & (df_m['FSIQ'] <140),['ppt_id','FSIQ','PIQ'] ]

    ppt_id  FSIQ  PIQ
2        3   139  150
4        5   137  134
6        7   138  131
9       10   133  147
22      23   135  134
30      31   133  132

## <font color=green>💬 Discussion point</font>
Why did you have to put parentheses around the two logical expressions?

## Setting values in Pandas data objects

Selectors - including slices, `loc` and `iloc` can also be used to set the values in `DataFrames` and `Series`. For example,

`df.loc[df.some_column < 1, 'some_column'] = 0`

will set all values less than 1 in _some_column_ to zero.

You can also combine slice selectors with slice setting of values. For example,

`df[['B', 'A']] = df[['A', 'B']]`

will swap two columns.

This last technique does not work with `loc` and `iloc` - see the [documentation](https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html) for details of how to do this with `loc` and `iloc`

## Deleting data

Now that we can select bits of our data objects, we can start to do things with the data. First, we will see how to delete bits.

### Deleting columns


## <font color=green>💬 Discussion point</font>

Our DataFrame has a strange column "Unnmamed: 0". What do you think it is?

There are a few ways we could delete this column. For example, using the selector operators we looked at above, we could keep just the columns we want, like this:

`df_m = df_m[['ppt_id', 'FSIQ', 'VIQ', 'PIQ', 'MRI_Count']]`

We are instead going to use the `drop` method. This takes as arguments:

- column name
- axis=n, where n=1 denotes a column, and n=0 denotes a row

Run the example below to see this:

In [17]:
# remove the column "Unnamed: 0" - an artefact from some earlier
# data processing
df_m = df_m.drop('Unnamed: 0', axis=1)
df_m.head(3)

   ppt_id  FSIQ  VIQ  PIQ  MRI_Count
0       1   133  132  124     816932
1       2   140  150  124    1001121
2       3   139  123  150    1038437

### Deleting rows

We can also use `drop()` to remove rows. If we know the index(es) of our rows, we can use `drop()`, as above (with axis=0).

If we have a condition, we can select what we want to keep. Let's say we need to remove participant with ppt_id=17 (perhaps they have withdrawn from the study). We could use the followig - run it:

In [18]:
df_m = df_m[df_m.ppt_id != 17]
df_m[15:18]

    ppt_id  FSIQ  VIQ  PIQ  MRI_Count
15      16    83   71   96     865363
17      18   100   96  102     945088
18      19   101  112   84     808020

## Reading in a second dataset


The code above has imported a set of clinic measurements. Now we need to read in further  information for the same participants. This is in a file called `brain_participant_info.csv`

## <font color=green>❓ Question</font>
Do the following:

1. Read in the csv file `brain_participant_info.csv` into a dataframe called `df_p`
1. Take a look at it using some of the `DataFrame` methods given above
1. Remove the artefact column, 'Unnamed: 0'
1. Remove participant ppt_id=17
1. Take a look at the DataFrame again, to check all is well

## <font color=green>⌨️ Your answer</font>

In [19]:
# Put your answer in this cell and the next one

# Read in the csv file
# YOU WRITE THIS
df_p = pd.read_csv("/content/brain_participant_info (1).txt")

# Take a look
# YOU WRITE THIS
df_p.head()
print(df_p.shape)
print(df_p.columns)
print(df_p.head())
print(df_p.describe())

(40, 6)
Index(['Unnamed: 0', 'ppt_id', 'Gender', 'Weight', 'Height', 'Diagnosed'], dtype='object')
   Unnamed: 0  ppt_id  Gender  Weight  Height Diagnosed
0           0       1  Female   118.0   645.0       Yes
1           1       2    Male     NaN   725.0        No
2           2       3    Male   143.0   733.0       Yes
3           3       4    Male   172.0   688.0        No
4           4       5  Female   147.0    65.0       Yes
       Unnamed: 0     ppt_id      Weight      Height
count   40.000000  40.000000   38.000000   39.000000
mean    19.500000  20.500000  151.052632  402.333333
std     11.690452  11.690452   23.478509  314.962599
min      0.000000   1.000000  106.000000   62.000000
25%      9.750000  10.750000  135.250000   68.500000
50%     19.500000  20.500000  146.500000  645.000000
75%     29.250000  30.250000  172.000000  686.500000
max     39.000000  40.000000  192.000000  765.000000

In [20]:
# Drop the 'Unnamed: 0' column
# YOU WRITE THIS
df_p.drop("Unnamed: 0", axis = 1)

# Remove ppt_id=17
# YOU WRITE THIS

df_p = df_p[df_p.ppt_id != 17]
# Take a look
# YOU WRITE THIS
df_p[15:18]

    Unnamed: 0  ppt_id  Gender  Weight  Height Diagnosed
15          15      16  Female   135.0    68.0       Yes
17          17      18    Male   178.0   735.0        No
18          18      19  Female   136.0   663.0       Yes

## Merging Datasets

Our two dataframes contain data about the same study participants. We can merge them.

## <font color=green>💬 Discussion point</font>

What identifies the rows in df_m that should be merged with those in df_p?

The code to do the merge is given below. Run it:

In [21]:
# create one merged DataFrame
df_all = df_m.merge(df_p, on = ['ppt_id'], how = 'left')
df_all.head()

,ppt_id,FSIQ,VIQ,PIQ,MRI_Count,Unnamed: 0,Gender,Weight,Height,Diagnosed
0,1,133,132,124,816932,0,Female,118.0,645.0,Yes
1,2,140,150,124,1001121,1,Male,NaN,725.0,No
2,3,139,123,150,1038437,2,Male,143.0,733.0,Yes
3,4,133,129,128,965353,3,Male,172.0,688.0,No
4,5,137,132,134,951545,4,Female,147.0,65.0,Yes

## <font color=green>💬 Discussion point</font>


Take a look at the [DataFrame.merge() documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html#pandas-dataframe-merge).

Can you explain the three arguments in the merge above?

## Aggregating data

- We use the `DataFrame.groupby()` method to aggregate data.
- It returns a `GroupBy` object
- There is also a `GroupBy` for `Series`.
- `GroupBy` has many useful methods - take a look at the [documentation](https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html#groupby)

Below is an exmaple of using `groupby()` to group be gender. Note that you nee the `numeric_only` argument to stop it trying to calculate the mean for non-numeric columns. Try it:

In [22]:
# Group our merged dataset by gender, and examine the mean

df_all.groupby("Gender").mean(numeric_only=True)

,ppt_id,FSIQ,VIQ,PIQ,MRI_Count,Unnamed: 0,Weight,Height
Gender,,,,,,,,
Female,19.789474,110.842105,108.263158,109.947368,863202.526316,18.789474,137.736842,376.736842
Male,21.350000,115.000000,115.250000,111.600000,954855.400000,20.350000,166.444444,413.052632

## <font color=green>❓ Question</font>

How do you think you aggregate by two columns? Try it below,

- aggregate by the gender and diagnosed columns
- compute the medians
- display only Height and Weight in your table

## <font color=green>⌨️ Your answer</font>

In [23]:
# What if you want to investigate two categorical variables?
# Group by gender and diagnosed, and show the medians of
# the four categories
# YOUR ANSWER HERE
df_all.groupby(["Gender", "Diagnosed"])[['Height','Weight']].median(numeric_only = True)

                  Height  Weight
Gender Diagnosed
Female No          645.0   139.0
       Yes         347.0   142.0
Male   No          688.0   172.0
       Yes          77.0   155.0

## Transposing DataFrames and GroupBys

- _Transposing_ a two dimensional data object reflects it about its diagonal
- Rows become columns, and columns become rows
- This is useful for getting data in the right form for presenting
- Examples of objects that cab be reflected
  - DataFrame
  - The display output of DataFrame operations, e.g. mean(), median(), describe()
- Use the method `transpose()`
- (the attribute `T` also works but is not so readable)
  
Run the example below, which flips the output of `describe()` for our dataset.

In [24]:
# Transpose summary statistics of the merged dataset
df_all.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
ppt_id,39.0,20.589744,11.829308,1.0,10.50,21.0,30.50,40.0
FSIQ,39.0,112.974359,24.205792,77.0,89.50,103.0,136.00,144.0
VIQ,39.0,111.846154,23.706027,71.0,90.00,112.0,129.00,150.0
PIQ,39.0,110.794872,22.717000,72.0,87.50,110.0,128.00,150.0
MRI_Count,39.0,910204.000000,72636.026973,790619.0,857127.00,905940.0,950567.00,1079549.0
Unnamed: 0,39.0,19.589744,11.829308,0.0,9.50,20.0,29.50,39.0
Weight,37.0,151.702703,23.453103,106.0,136.00,147.0,172.00,192.0
Height,38.0,394.894737,315.699634,62.0,68.25,635.0,682.25,765.0

## <font color=green>❓ Question</font>

`transpose()` will also work with the output of `groupby()`. Try this:

- Group `df_all` by gender and diagnosed
- Select just the MRI_Count column
- Get summary statistics for this column
- Transpose the summary statistics

## <font color=green>⌨️ Your answer</font>

In [25]:
# Your answer below - you should be able to do this on one line
# Group by gender and diagnosed
# Select MRI_Count
# Get summary stats
# Transpose them
df_all.groupby(['Gender','Diagnosed'])
df_all['MRI_Count'].describe().transpose()

count    3.900000e+01
mean     9.102040e+05
std      7.263603e+04
min      7.906190e+05
25%      8.571270e+05
50%      9.059400e+05
75%      9.505670e+05
max      1.079549e+06
Name: MRI_Count, dtype: float64

## Working with missing data

### Finding missing data

Let's take another look at the summary stats for our aggregated data - run this:

In [26]:
# Get summary stats
df_all.describe()

,ppt_id,FSIQ,VIQ,PIQ,MRI_Count,Unnamed: 0,Weight,Height
count,39.000000,39.000000,39.000000,39.000000,3.900000e+01,39.000000,37.000000,38.000000
mean,20.589744,112.974359,111.846154,110.794872,9.102040e+05,19.589744,151.702703,394.894737
std,11.829308,24.205792,23.706027,22.717000,7.263603e+04,11.829308,23.453103,315.699634
min,1.000000,77.000000,71.000000,72.000000,7.906190e+05,0.000000,106.000000,62.000000
25%,10.500000,89.500000,90.000000,87.500000,8.571270e+05,9.500000,136.000000,68.250000
50%,21.000000,103.000000,112.000000,110.000000,9.059400e+05,20.000000,147.000000,635.000000
75%,30.500000,136.000000,129.000000,128.000000,9.505670e+05,29.500000,172.000000,682.250000
max,40.000000,144.000000,150.000000,150.000000,1.079549e+06,39.000000,192.000000,765.000000

## <font color=green>💬 Discussion point</font>


Take a look at the counts of our columns.
 - Can you see anything out of place? What could be the problem?
 - Looking at the [DataFrame documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#conversion) can you see a method that might help detect this problem?

## <font color=green>❓ Question</font>

Using the method you found above,

1. create a new `DataFrame` which records whether or not each value in `df_all` is missing
1. Use `loc` with this new `DataFrame`, and a logical selector, display all rows where either Height or Weight are missing

__Hint:__ Remember to use the correct logical operator (e.g. &, |) and remember to use parentheses around the parts of your logical expression.

## <font color=green>⌨️ Your answer</font>

In [27]:
# Which rows have mssing Heights or Weights?
# Complete the code below

# First make a DataFrame of True / False for all missing values
missing = df_all.isna()

# Now use .loc to select those rows where Height is missing or Weight is missing
missing.loc[(missing['Height']| missing['Weight'])]

,ppt_id,FSIQ,VIQ,PIQ,MRI_Count,Unnamed: 0,Gender,Weight,Height,Diagnosed
1,False,False,False,False,False,False,False,True,False,False
19,False,False,False,False,False,False,False,True,True,False

### How are we going to deal with the missing data?

We could:

- delete (method `DataFrame.dropna()` does this)
- interpolate with new values (Pandas supports this)
- impute with mean values

We will do the latter. We will make use of the `DataFrame.fillna()` method.

## <font color=green>💬 Discussion point</font>

Take a look at the [documentation for DataFrame.fillna()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.fillna.html#pandas.DataFrame.fillna)

We will use this argument - what does it do?
  - `value`

The below code does a `fillna()` on Weight, filling with the mean of Weight. Try it, and note that the previous missing weight in the second row now takes the mean value:

In [28]:
# Fill NAs and display

# Before...
print( df_all.loc[:,['Weight']].head(3) )

# Let's take a look at the mean first, so we know what to expect
mean = df_all.loc[:,['Weight']].mean()
print('\nmean:', mean)

# After..
df_all.loc[:,['Weight']].fillna(mean).head(3)

   Weight
0   118.0
1     NaN
2   143.0

mean: Weight    151.702703
dtype: float64

       Weight
0  118.000000
1  151.702703
2  143.000000

## <font color=green>💬 Discussion point</font>

- Anyone see a problem with this approach?
- How can we overcome this?

### `transform()`

We will use the `transform` method, which works on `Series` and `DataFrames`

- `transform()` takes as an argument the name of a method on the object it is transforming
- the method name is given as a string
- it returns the result of applying that method to the DataFrame.

Take a look at the example below:

In [30]:
# Replace all values with the mean for the gender

df_all.groupby("Gender").transform("mean", numeric_only=True).head()

,ppt_id,FSIQ,VIQ,PIQ,MRI_Count,Unnamed: 0,Weight,Height
0,19.789474,110.842105,108.263158,109.947368,863202.526316,18.789474,137.736842,376.736842
1,21.350000,115.000000,115.250000,111.600000,954855.400000,20.350000,166.444444,413.052632
2,21.350000,115.000000,115.250000,111.600000,954855.400000,20.350000,166.444444,413.052632
3,21.350000,115.000000,115.250000,111.600000,954855.400000,20.350000,166.444444,413.052632
4,19.789474,110.842105,108.263158,109.947368,863202.526316,18.789474,137.736842,376.736842

### Putting it all together

Now that we can transform all of our values to means, let's use `fillna()` to change just those where we have no value.

Take a look at the answer below.

In [29]:
# Get means for gender
means_for_gender = df_all.groupby("Gender").transform("mean", numeric_only=True)

# Use this to fill in the NAs - this time inplace is True
df_all.loc[:,["Weight"]] = df_all.loc[:,["Weight"]].fillna(means_for_gender)

df_all.head()

,ppt_id,FSIQ,VIQ,PIQ,MRI_Count,Unnamed: 0,Gender,Weight,Height,Diagnosed
0,1,133,132,124,816932,0,Female,118.000000,645.0,Yes
1,2,140,150,124,1001121,1,Male,166.444444,725.0,No
2,3,139,123,150,1038437,2,Male,143.000000,733.0,Yes
3,4,133,129,128,965353,3,Male,172.000000,688.0,No
4,5,137,132,134,951545,4,Female,147.000000,65.0,Yes

## <font color=green>❓ Question</font>

Fill in all empty Heights with the mean for participant gender.

## <font color=green>⌨️ Your answer</font>

In [31]:
# Fill missing Height values with the mean for the Gender
# YOUR ANSWER HERE
df_all.loc[:,["Height"]] = df_all.loc[:,["Height"]].fillna(means_for_gender)

## <font color=green>💬 Discussion point</font>

Can you see how both Height and Weight empty values could have been filled at the same time?

## <font color=green>❓ Question</font>

Check to see if there are any empty values in the aggregated dataset.

## <font color=green>⌨️ Your answer</font>

In [32]:
# Now let's check to see if we have any missing values
# YOUR ANSWER HERE
df_all.isnull().sum()

ppt_id        0
FSIQ          0
VIQ           0
PIQ           0
MRI_Count     0
Unnamed: 0    0
Gender        0
Weight        0
Height        0
Diagnosed     0
dtype: int64

## Exporting data

Now we've done our transofrmations and analysis, how do we get the data out, e.g. in to another program, or for publication?

Pandas has support for export to many formats, as described in [the documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#serialization-io-conversion).

Here's one useful idea, sending a transposed summary of gender and diagnosed to the clipboard, so that you can paste it in to another program. Try it:

__NOTE__ This might not work with all operating systems

In [33]:
# Prepare your tables for publication?
# Copy to clipboard and then format in Excel

df_all.groupby(['Gender','Diagnosed']).describe().transpose().to_clipboard()

PyperclipException:
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit
    https://pyperclip.readthedocs.io/en/latest/index.html#not-implemented-error

## <font color=green>❓ Question</font>

Referring to [the documentation](https://pandas.pydata.org/pandas-docs/stable/reference/frame.html#serialization-io-conversion), export a transposed summary of gender and diganosed to an Excel, Stata or Latex file (depending on your preference), and open in another program (e.g. Excel, Stata, or your favourite editor).

## <font color=green>⌨️ Your answer</font>

In [35]:
# Export some data to a file
df_all.groupby(['Gender','Diagnosed']).describe().transpose().to_excel(summary.xlsx)

NameError: name 'summary' is not defined